#!/bin/sh
ENUM_FILE="enum.as"

DATE=$(date '+%H:%M:%S');
echo ${DATE}

sed -r -i 's/\[[0-9]*\]$//g' ./${ENUM_FILE}
sed -r -i 's/\t/,/g' ./${ENUM_FILE}


sed -r -i 's/CompletelyReleased$/_CompletelyReleased/g' ./${ENUM_FILE}
sed -r -i 's/TouchApplyRelease$/_TouchApplyRelease/g' ./${ENUM_FILE}
sed -r -i 's/TouchBrkRearRight$/_TouchBrkRearRight/g' ./${ENUM_FILE}
sed -r -i 's/OpenBrkRearRight$/_OpenBrkRearRight/g' ./${ENUM_FILE}
sed -r -i 's/StatApplyRelease$/_StatApplyRelease/g' ./${ENUM_FILE}
sed -r -i 's/StepClsRearRight$/_StepClsRearRight/g' ./${ENUM_FILE}
sed -r -i 's/TouchBrkRearLeft$/_TouchBrkRearLeft/g' ./${ENUM_FILE}
sed -r -i 's/UnderRangeContns$/_UnderRangeContns/g' ./${ENUM_FILE}
sed -r -i 's/ApplyAndRelease$/_ApplyAndRelease/g' ./${ENUM_FILE}
sed -r -i 's/ClmpFLoWithTarI$/_ClmpFLoWithTarI/g' ./${ENUM_FILE}
sed -r -i 's/ClsBrkRearRight$/_ClsBrkRearRight/g' ./${ENUM_FILE}
sed -r -i 's/OpenBrkRearLeft$/_OpenBrkRearLeft/g' ./${ENUM_FILE}
sed -r -i 's/OverRangeContns$/_OverRangeContns/g' ./${ENUM_FILE}
sed -r -i 's/RollrbenchApply$/_RollrbenchApply/g' ./${ENUM_FILE}
sed -r -i 's/StepClsRearLeft$/_StepClsRearLeft/g' ./${ENUM_FILE}
sed -r -i 's/ClsBrkRearLeft$/_ClsBrkRearLeft/g' ./${ENUM_FILE}
sed -r -i 's/EnterMntneMode$/_EnterMntneMode/g' ./${ENUM_FILE}
sed -r -i 's/PwrDwnUnexpted$/_PwrDwnUnexpted/g' ./${ENUM_FILE}
sed -r -i 's/EpbReclmpExcd$/_EpbReclmpExcd/g' ./${ENUM_FILE}
sed -r -i 's/MntnNotExited$/_MntnNotExited/g' ./${ENUM_FILE}
sed -r -i 's/PadAdjustment$/_PadAdjustment/g' ./${ENUM_FILE}
sed -r -i 's/UnderRangeTmp$/_UnderRangeTmp/g' ./${ENUM_FILE}
sed -r -i 's/AssmblyCheck$/_AssmblyCheck/g' ./${ENUM_FILE}
sed -r -i 's/CmplyRelease$/_CmplyRelease/g' ./${ENUM_FILE}
sed -r -i 's/DynDgrdDecel$/_DynDgrdDecel/g' ./${ENUM_FILE}
sed -r -i 's/ExitMntnMode$/_ExitMntnMode/g' ./${ENUM_FILE}
sed -r -i 's/FactoryReset$/_FactoryReset/g' ./${ENUM_FILE}
sed -r -i 's/HostEpbResrc$/_HostEpbResrc/g' ./${ENUM_FILE}
sed -r -i 's/HostHpsResrc$/_HostHpsResrc/g' ./${ENUM_FILE}
sed -r -i 's/NotIndicated$/_NotIndicated/g' ./${ENUM_FILE}
sed -r -i 's/NotRequested$/_NotRequested/g' ./${ENUM_FILE}
sed -r -i 's/NotSupported$/_NotSupported/g' ./${ENUM_FILE}
sed -r -i 's/OverRangeTmp$/_OverRangeTmp/g' ./${ENUM_FILE}
sed -r -i 's/PwrSplyUnder$/_PwrSplyUnder/g' ./${ENUM_FILE}
sed -r -i 's/ReClmpBumpup$/_ReClmpBumpup/g' ./${ENUM_FILE}
sed -r -i 's/TouchBrkBoth$/_TouchBrkBoth/g' ./${ENUM_FILE}
sed -r -i 's/CmplyOpened$/_CmplyOpened/g' ./${ENUM_FILE}
sed -r -i 's/DynDgrdSlip$/_DynDgrdSlip/g' ./${ENUM_FILE}
sed -r -i 's/EmgyStopped$/_EmgyStopped/g' ./${ENUM_FILE}
sed -r -i 's/EpbOperLimn$/_EpbOperLimn/g' ./${ENUM_FILE}
sed -r -i 's/FSNotFailed$/_FSNotFailed/g' ./${ENUM_FILE}
sed -r -i 's/HoldApplied$/_HoldApplied/g' ./${ENUM_FILE}
sed -r -i 's/HpsOperLimn$/_HpsOperLimn/g' ./${ENUM_FILE}
sed -r -i 's/MntnEntered$/_MntnEntered/g' ./${ENUM_FILE}
sed -r -i 's/NotReliable$/_NotReliable/g' ./${ENUM_FILE}
sed -r -i 's/NotRequired$/_NotRequired/g' ./${ENUM_FILE}
sed -r -i 's/OpenBrkBoth$/_OpenBrkBoth/g' ./${ENUM_FILE}
sed -r -i 's/ParkApplied$/_ParkApplied/g' ./${ENUM_FILE}
sed -r -i 's/PwrSplyOver$/_PwrSplyOver/g' ./${ENUM_FILE}
sed -r -i 's/ReClsBraked$/_ReClsBraked/g' ./${ENUM_FILE}
sed -r -i 's/Rollerbench$/_Rollerbench/g' ./${ENUM_FILE}
sed -r -i 's/StatRelease$/_StatRelease/g' ./${ENUM_FILE}
sed -r -i 's/StepClsBoth$/_StepClsBoth/g' ./${ENUM_FILE}
sed -r -i 's/TouchBraked$/_TouchBraked/g' ./${ENUM_FILE}
sed -r -i 's/Unavailable$/_Unavailable/g' ./${ENUM_FILE}
sed -r -i 's/WithinRange$/_WithinRange/g' ./${ENUM_FILE}
sed -r -i 's/AdpvBraked$/_AdpvBraked/g' ./${ENUM_FILE}
sed -r -i 's/ClsBrkBoth$/_ClsBrkBoth/g' ./${ENUM_FILE}
sed -r -i 's/CtrlPaused$/_CtrlPaused/g' ./${ENUM_FILE}
sed -r -i 's/DataResetA$/_DataResetA/g' ./${ENUM_FILE}
sed -r -i 's/DataResetB$/_DataResetB/g' ./${ENUM_FILE}
sed -r -i 's/DynOverlay$/_DynOverlay/g' ./${ENUM_FILE}
sed -r -i 's/EmgyPaused$/_EmgyPaused/g' ./${ENUM_FILE}
sed -r -i 's/EmgyResume$/_EmgyResume/g' ./${ENUM_FILE}
sed -r -i 's/NotMatched$/_NotMatched/g' ./${ENUM_FILE}
sed -r -i 's/OpenBraked$/_OpenBraked/g' ./${ENUM_FILE}
sed -r -i 's/OutOfRange$/_OutOfRange/g' ./${ENUM_FILE}
sed -r -i 's/PwrSplyCdn$/_PwrSplyCdn/g' ./${ENUM_FILE}
sed -r -i 's/ReClmpPost$/_ReClmpPost/g' ./${ENUM_FILE}
sed -r -i 's/ReClsBrake$/_ReClsBrake/g' ./${ENUM_FILE}
sed -r -i 's/TouchApply$/_TouchApply/g' ./${ENUM_FILE}
sed -r -i 's/TouchBrake$/_TouchBrake/g' ./${ENUM_FILE}
sed -r -i 's/Transition$/_Transition/g' ./${ENUM_FILE}
sed -r -i 's/UnderRange$/_UnderRange/g' ./${ENUM_FILE}
sed -r -i 's/Unexpected$/_Unexpected/g' ./${ENUM_FILE}
sed -r -i 's/Activated$/_Activated/g' ./${ENUM_FILE}
sed -r -i 's/AdpvApply$/_AdpvApply/g' ./${ENUM_FILE}
sed -r -i 's/AdpvBrake$/_AdpvBrake/g' ./${ENUM_FILE}
sed -r -i 's/AsmblyChk$/_AsmblyChk/g' ./${ENUM_FILE}
sed -r -i 's/ClsBraked$/_ClsBraked/g' ./${ENUM_FILE}
sed -r -i 's/CmplyOpen$/_CmplyOpen/g' ./${ENUM_FILE}
sed -r -i 's/CtrlPause$/_CtrlPause/g' ./${ENUM_FILE}
sed -r -i 's/DataStorg$/_DataStorg/g' ./${ENUM_FILE}
sed -r -i 's/EmgyPause$/_EmgyPause/g' ./${ENUM_FILE}
sed -r -i 's/HldBraked$/_HldBraked/g' ./${ENUM_FILE}
sed -r -i 's/HostAvlty$/_HostAvlty/g' ./${ENUM_FILE}
sed -r -i 's/HostSwVer$/_HostSwVer/g' ./${ENUM_FILE}
sed -r -i 's/Indicated$/_Indicated/g' ./${ENUM_FILE}
sed -r -i 's/NotPassed$/_NotPassed/g' ./${ENUM_FILE}
sed -r -i 's/OpenBrake$/_OpenBrake/g' ./${ENUM_FILE}
sed -r -i 's/OverRange$/_OverRange/g' ./${ENUM_FILE}
sed -r -i 's/ParkApply$/_ParkApply/g' ./${ENUM_FILE}
sed -r -i 's/PreFailed$/_PreFailed/g' ./${ENUM_FILE}
sed -r -i 's/PrePassed$/_PrePassed/g' ./${ENUM_FILE}
sed -r -i 's/ReClmpPre$/_ReClmpPre/g' ./${ENUM_FILE}
sed -r -i 's/Releasing$/_Releasing/g' ./${ENUM_FILE}
sed -r -i 's/Requested$/_Requested/g' ./${ENUM_FILE}
sed -r -i 's/SemiFinal$/_SemiFinal/g' ./${ENUM_FILE}
sed -r -i 's/StatApply$/_StatApply/g' ./${ENUM_FILE}
sed -r -i 's/StepApply$/_StepApply/g' ./${ENUM_FILE}
sed -r -i 's/StepClose$/_StepClose/g' ./${ENUM_FILE}
sed -r -i 's/Applying$/_Applying/g' ./${ENUM_FILE}
sed -r -i 's/ClsBrake$/_ClsBrake/g' ./${ENUM_FILE}
sed -r -i 's/DynActvn$/_DynActvn/g' ./${ENUM_FILE}
sed -r -i 's/DynApply$/_DynApply/g' ./${ENUM_FILE}
sed -r -i 's/EmgyStop$/_EmgyStop/g' ./${ENUM_FILE}
sed -r -i 's/HldApply$/_HldApply/g' ./${ENUM_FILE}
sed -r -i 's/HldBrake$/_HldBrake/g' ./${ENUM_FILE}
sed -r -i 's/HpsAvlty$/_HpsAvlty/g' ./${ENUM_FILE}
sed -r -i 's/Inactive$/_Inactive/g' ./${ENUM_FILE}
sed -r -i 's/MotIdleI$/_MotIdleI/g' ./${ENUM_FILE}
sed -r -i 's/MotOvrun$/_MotOvrun/g' ./${ENUM_FILE}
sed -r -i 's/MotStuck$/_MotStuck/g' ./${ENUM_FILE}
sed -r -i 's/NoResult$/_NoResult/g' ./${ENUM_FILE}
sed -r -i 's/OpenCirc$/_OpenCirc/g' ./${ENUM_FILE}
sed -r -i 's/Released$/_Released/g' ./${ENUM_FILE}
sed -r -i 's/Required$/_Required/g' ./${ENUM_FILE}
sed -r -i 's/ReqVldty$/_ReqVldty/g' ./${ENUM_FILE}
sed -r -i 's/Reversed$/_Reversed/g' ./${ENUM_FILE}
sed -r -i 's/SlopAndT$/_SlopAndT/g' ./${ENUM_FILE}
sed -r -i 's/SlopOnly$/_SlopOnly/g' ./${ENUM_FILE}
sed -r -i 's/StepOpen$/_StepOpen/g' ./${ENUM_FILE}
sed -r -i 's/TouchBrk$/_TouchBrk/g' ./${ENUM_FILE}
sed -r -i 's/VehDecel$/_VehDecel/g' ./${ENUM_FILE}
sed -r -i 's/VrntItem$/_VrntItem/g' ./${ENUM_FILE}
sed -r -i 's/Closing$/_Closing/g' ./${ENUM_FILE}
sed -r -i 's/Dynamic$/_Dynamic/g' ./${ENUM_FILE}
sed -r -i 's/Freerun$/_Freerun/g' ./${ENUM_FILE}
sed -r -i 's/Initial$/_Initial/g' ./${ENUM_FILE}
sed -r -i 's/Invalid$/_Invalid/g' ./${ENUM_FILE}
sed -r -i 's/Limited$/_Limited/g' ./${ENUM_FILE}
sed -r -i 's/Matched$/_Matched/g' ./${ENUM_FILE}
sed -r -i 's/Missing$/_Missing/g' ./${ENUM_FILE}
sed -r -i 's/MotOvld$/_MotOvld/g' ./${ENUM_FILE}
sed -r -i 's/NotDone$/_NotDone/g' ./${ENUM_FILE}
sed -r -i 's/NotUsed$/_NotUsed/g' ./${ENUM_FILE}
sed -r -i 's/OpenBrk$/_OpenBrk/g' ./${ENUM_FILE}
sed -r -i 's/Opening$/_Opening/g' ./${ENUM_FILE}
sed -r -i 's/Reclamp$/_Reclamp/g' ./${ENUM_FILE}
sed -r -i 's/Release$/_Release/g' ./${ENUM_FILE}
sed -r -i 's/Running$/_Running/g' ./${ENUM_FILE}
sed -r -i 's/Standby$/_Standby/g' ./${ENUM_FILE}
sed -r -i 's/Started$/_Started/g' ./${ENUM_FILE}
sed -r -i 's/StepCls$/_StepCls/g' ./${ENUM_FILE}
sed -r -i 's/Suspect$/_Suspect/g' ./${ENUM_FILE}
sed -r -i 's/Unknown$/_Unknown/g' ./${ENUM_FILE}
sed -r -i 's/WhlSlip$/_WhlSlip/g' ./${ENUM_FILE}
sed -r -i 's/Active$/_Active/g' ./${ENUM_FILE}
sed -r -i 's/Bumpup$/_Bumpup/g' ./${ENUM_FILE}
sed -r -i 's/ClsBrk$/_ClsBrk/g' ./${ENUM_FILE}
sed -r -i 's/Failed$/_Failed/g' ./${ENUM_FILE}
sed -r -i 's/Inrush$/_Inrush/g' ./${ENUM_FILE}
sed -r -i 's/Noload$/_Noload/g' ./${ENUM_FILE}
sed -r -i 's/Normal$/_Normal/g' ./${ENUM_FILE}
sed -r -i 's/Passed$/_Passed/g' ./${ENUM_FILE}
sed -r -i 's/PbcPrm$/_PbcPrm/g' ./${ENUM_FILE}
sed -r -i 's/Range1$/_Range1/g' ./${ENUM_FILE}
sed -r -i 's/Range2$/_Range2/g' ./${ENUM_FILE}
sed -r -i 's/Range3$/_Range3/g' ./${ENUM_FILE}
sed -r -i 's/Range4$/_Range4/g' ./${ENUM_FILE}
sed -r -i 's/Range5$/_Range5/g' ./${ENUM_FILE}
sed -r -i 's/SeqMon$/_SeqMon/g' ./${ENUM_FILE}
sed -r -i 's/Static$/_Static/g' ./${ENUM_FILE}
sed -r -i 's/Apply$/_Apply/g' ./${ENUM_FILE}
sed -r -i 's/Bmpup$/_Bmpup/g' ./${ENUM_FILE}
sed -r -i 's/Error$/_Error/g' ./${ENUM_FILE}
sed -r -i 's/Fault$/_Fault/g' ./${ENUM_FILE}
sed -r -i 's/Final$/_Final/g' ./${ENUM_FILE}
sed -r -i 's/ModeB$/_ModeB/g' ./${ENUM_FILE}
sed -r -i 's/ModeO$/_ModeO/g' ./${ENUM_FILE}
sed -r -i 's/Right$/_Right/g' ./${ENUM_FILE}
sed -r -i 's/TOnly$/_TOnly/g' ./${ENUM_FILE}
sed -r -i 's/Valid$/_Valid/g' ./${ENUM_FILE}
sed -r -i 's/Both$/_Both/g' ./${ENUM_FILE}
sed -r -i 's/Diag$/_Diag/g' ./${ENUM_FILE}
sed -r -i 's/Done$/_Done/g' ./${ENUM_FILE}
sed -r -i 's/Idle$/_Idle/g' ./${ENUM_FILE}
sed -r -i 's/Left$/_Left/g' ./${ENUM_FILE}
sed -r -i 's/Load$/_Load/g' ./${ENUM_FILE}
sed -r -i 's/None$/_None/g' ./${ENUM_FILE}
sed -r -i 's/OSOK$/_OSOK/g' ./${ENUM_FILE}
sed -r -i 's/Post$/_Post/g' ./${ENUM_FILE}
sed -r -i 's/Stop$/_Stop/g' ./${ENUM_FILE}
sed -r -i 's/Max$/_Max/g' ./${ENUM_FILE}
sed -r -i 's/NOK$/_NOK/g' ./${ENUM_FILE}
sed -r -i 's/Pre$/_Pre/g' ./${ENUM_FILE}
sed -r -i 's/Yes$/_Yes/g' ./${ENUM_FILE}
sed -r -i 's/No$/_No/g' ./${ENUM_FILE}
sed -r -i 's/OK$/_OK/g' ./${ENUM_FILE}


sed -r -i 's/(_.*)_/\1/' ./${ENUM_FILE}
sed -r -i 's/__/_/' ./${ENUM_FILE}


DATE=$(date '+%H:%M:%S');
echo ${DATE}